### Create an Entitity
POST http://localhost:3000/v1/entity
x-app-audit-event: create-entity
authorization: Bearer PUBLIC
content-type: application/json

{
    "name": "Bot"
}

### Get all Entities
GET http://localhost:3000/v1/entity
x-app-audit-event: get-entity
authorization: Bearer PUBLIC

### Get Entitiy by ID
GET http://localhost:3000/v1/entity/1
x-app-audit-event: get-entity-by-id
authorization: Bearer PUBLIC

### Update an Entitiy by ID
PUT http://localhost:3000/v1/entity/1
x-app-audit-event: update-entitiy-by-id
authorization: Bearer PUBLIC
content-type: application/json

{
    "name": "Bot Update"
}

### Delete an Entitiy by ID
DELETE http://localhost:3000/v1/entity/1
x-app-audit-event: delete-entitiy-by-id
authorization: Bearer PUBLIC

### Get Audit (Admin)
GET http://localhost:3000/admin/v1/audit
x-app-audit-event: admin-audit
authorization: Bearer ADMINISTRATOR

### Get Audit by Event (Admin)
GET http://localhost:3000/admin/v1/audit/admin-audit-by-event
x-app-audit-event: admin-audit-by-event
authorization: Bearer ADMINISTRATOR


### Get Route Errors (Admin)
GET http://localhost:3000/admin/v1/route-error
x-app-audit-event: admin-route-errors
authorization: Bearer ADMINISTRATOR